### ISSUE TITLE
Create merch suggestion call-to-action section

### ISSUE THREAD

**Issue by maxellmilay** [upcsg-org/upcsg-website-v2#9]
![image](https://github.com/user-attachments/assets/ca08f81b-ded1-4cd0-bf39-5afbaa570388)

**Comment by Depyter** [comment]
Apil sad ang overlay sa submission form for merch ani? If so, what package ang gamiton for the image upload or pure nextjs? @maxellmilay

**Comment by maxellmilay** [comment]
@Depyter let's make the UI for this section first, separate issue na ang upload image feature

**Comment by Depyter** [comment]
So included ang UI for the submission? @maxellmilay

**Comment by maxellmilay** [comment]
@Depyter for this issue, just implement the UI specified sa screenshot. But if the design exists for uploading an image, you can do that as well, ayaw lang sa ang feature

**Comment by Depyter** [comment]
![Screenshot 2024-07-23 at 10 51 32 PM](https://github.com/user-attachments/assets/32df8a20-7c53-4ce5-9519-0fad2727229f)
<img width="284" alt="Screenshot 2024-07-23 at 10 52 37 PM" src="https://github.com/user-attachments/assets/f9a1032c-a0ae-42a4-9716-8e0227ce7797">
<img width="295" alt="Screenshot 2024-07-23 at 10 57 15 PM" src="https://github.com/user-attachments/assets/11591c03-c0a5-47a8-b349-b4d9dae8153a">
![Screenshot 2024-07-23 at 11 00 23 PM](https://github.com/user-attachments/assets/6c9a8db9-52fd-43f7-9625-e6a204a0dbcd)
<img width="284" alt="Screenshot 2024-07-23 at 10 52 19 PM" src="https://github.com/user-attachments/assets/22e369eb-9549-4f29-91aa-5b931548ceb4">

Both are from one import coming from google font.
### **Ig this is a skill issue**

**Comment by maxellmilay** [comment]
@Depyter I have used that font in the previous version of this site. Don't worry about it if it does not work, I'll fix it myself later

**Comment by Depyter** [comment]
@maxellmilay I got it working lang,  wanted to share kay it looks so stupid.
